### ISSUE TITLE
Failed to deploy a contract on a subchain

### ISSUE THREAD

**Issue by foreso-GitHub** [MOACChain/moac-core#34]
Hi mdranger, I tried to deploy a contract (which is very simple) on a subchain, and I can get the transaction hash after the deploy.  
0x7de43c393563540aa6c5d9f8bb41b59e75c9bdaa92eae456b47f32c706030ba0

But I find the deployment looks failed in the scs log:
DEBUG[07-27|11:06:59.386] 102:contractaddr:0xac700eF970de3e51BC587CAF89598eefc86c5cFb 
...
**_ERROR[07-27|11:06:59.543] 102:failed to Unmarshal err: unexpected end of JSON input_** 
DEBUG[07-27|11:06:59.551] 102:contractInfo.Storage:map[] 

GetDappState, return 0.  So looks this contract has not be deployed successfully.

Can you have a look in the contract and logs I attached?  If possible, please provide some idea/suggestion how I can update it.  Thanks!

**Comment by foreso-GitHub** [comment]
Contract and logs.
[contract.txt](https://github.com/MOACChain/moac-core/files/2234362/contract.txt)
[vnode.log](https://github.com/MOACChain/moac-core/files/2234363/vnode.log)
[scs.log](https://github.com/MOACChain/moac-core/files/2234364/scs.log)

**Comment by mdranger** [comment]
This may caused by the solidity compiler you used. We found out recently that if the contract is compiled with solidity compiler later than 0.21 version, it may cause this error: 
failed to Unmarshal err: unexpected end of JSON input. 
You can try to use an older solidity to compile the contract and deploy again.
We already fixed this bug and will release a new version soon.
Thanks very much for your help.

**Comment by foreso-GitHub** [comment]
Thanks mdranger. 

>with solidity compiler later than 0.21 version, it may cause this error:
You mean I should use lower version of solc, than 0.4.21, right?

Today I changed the solc to 0.4.19, but this error still happened.

**Comment by foreso-GitHub** [comment]
Hi @mdranger , I updated the vnode client to nuwa1.0.0.  Because I did not find any new scs client, so I still use the scs client of pangu0.8.4.  BUT, I still cannot deploy smart contract on subchain successfully.  The same error: "**failed to Unmarshal err: unexpected end of JSON input**" still exists.

I had a look in the log of scs server.  Then I found the "via" in the TX in the log looks abnormal.

======
DEBUG[08-01|17:15:47.694] 169:tx:
	TX(db8f57ce9e37fcdd2289c58b42ac562b8c85aae7c0b20381c0ddba80bb96865b)
	Contract: false
	From:     da4c7a63131c3f1a579dd3e7198f527e92d37178
	To:       9533774860608cfa49c9d0d8090f86310a86cb77
	Nonce:    26
	GasPrice: 0x0
	GasLimit  0x0
	Value:    0x0
	Data:     0x6060604052341561000f57600080fd5b6064600055610108806100236000396000f300606060405260043610605c5763ffffffff7c01000000000000000000000000000000000000000000000000000000006000350416630dbe671f8114606157806320965255146083578063d732d955146093578063e8927fbc1460a3575b600080fd5b3415606b57600080fd5b607160b3565b60405190815260200160405180910390f35b3415608d57600080fd5b607160b9565b3415609d57600080fd5b607160bf565b341560ad57600080fd5b607160ce565b60005481565b60005490565b60008054600019019081905590565b6000805460010190819055905600a165627a7a723058206a9cc8bda5a2b12f1e00225fe84cc181a88e742921c0a0a897ac4f5515f115010029
	V:        0xee
	R:        0x5beeccabb98e282cde7841f2992ea6fb835a15adbefa2238fb421bdc20b7f2f9
	S:        0xcf7e5e2e4a60155fef83ece6051c5a1959de108a7c5cf898d3ebead0835d663
	Hex:      f901a21a808080949533774860608cfa49c9d0d8090f86310a86cb7780b9012b6060604052341561000f57600080fd5b6064600055610108806100236000396000f300606060405260043610605c5763ffffffff7c01000000000000000000000000000000000000000000000000000000006000350416630dbe671f8114606157806320965255146083578063d732d955146093578063e8927fbc1460a3575b600080fd5b3415606b57600080fd5b607160b3565b60405190815260200160405180910390f35b3415608d57600080fd5b607160b9565b3415609d57600080fd5b607160bf565b341560ad57600080fd5b607160ce565b60005481565b60005490565b60008054600019019081905590565b6000805460010190819055905600a165627a7a723058206a9cc8bda5a2b12f1e00225fe84cc181a88e742921c0a0a897ac4f5515f1150100290194ca10ca46c36eb845d405be42fa738c8d4145200981eea05beeccabb98e282cde7841f2992ea6fb835a15adbefa2238fb421bdc20b7f2f9a00cf7e5e2e4a60155fef83ece6051c5a1959de108a7c5cf898d3ebead0835d663
	SysCnt:	  0
	ShardingFlag: 1
	**Via:	  ?蔉胣窫?綛鷖實AE** 	
 
DEBUG[08-01|17:15:47.802] 64:Trie cache stats after commit         misses=19 unloads=0

======

It should be a standard address, but not likes "from" and "to" shows as Hex, it changed to a messy code.  Is it probably the reason of this error?  Or if there is new scs server client and you think it can fix this error, please share it with me.  Thanks!

**Comment by foreso-GitHub** [comment]
Have found the reason.

In the Tx, the nonce should be the nonce of this sender in this subchain (the contract address of subchainbase.sol).  But I always used the nonce of this sender of the main chain.  That's way no contract was deployed.

We'd better update the doc and emphasize it should be the nonce of subchain in B4 part of https://github.com/MOACChain/moac-core/wiki/DAPP%E5%BC%80%E5%8F%91%E8%80%85%E6%8C%87%E5%8D%97.

**Comment by foreso-GitHub** [comment]
Have notified XuQing to update the doc.
